### ISSUE TITLE
Marko generating .js file in a typescript project

### ISSUE THREAD

**Issue by devfabiorm** [marko-js/express#1]
### Details

Well, I don't know exactly if it's indeed a problem, after all I still new using marko, but I'm using typescript but when marko compiles the marko file it generates a *.js file. I don't if I have to do a further configuration but I didn't find any docs describing a how-to.

### Expected Behavior

Generate a .ts file

### Actual Behavior

Generate .js file

### Possible Fix

I'm still studying a possible solution.

### Your Environment

I'm using Windows 10, node v12.19.0, marko v4.23.9, @marko/express v1.0.0, ts-node.dev v1.0.0, typescript 4.0.5

### Steps to Reproduce

Link for the project: https://github.com/devfabiorm/casa-do-codigo

1.  Clone the project
2. Delete the *.js file in src/app/views/livros/lista
3. run the script start

**Comment by DylanPiercey** [comment]
Marko does not yet support outputting `.ts`. Having said that, when using Marko 5 the default is that things are handled in memory and no `.js` file is output at all. You can add a `.d.ts` next to your Marko templates to get some level of typing, however full ts support will come in the future.
