### ISSUE TITLE
Middleware function isn't exported properly

### ISSUE THREAD

**Issue by GingerAdonis** [marko-js/express#2]
## Version
`1.0.0`

### Details

The readme suggests to import the middleware as `import markoMiddleware from '@marko/express';`. However, when calling the function Node.js throws an error: `TypeError: markoMiddleware is not a function`. This suggests the library isn't exporting the function properly.

### Expected Behavior

Default import returns middleware function.

### Actual Behavior

Default import returns an object with `default` property which contains the actual middleware function.

### Workaround

Replace `app.use(markoMiddleware());` with `app.use(markoMiddleware.default());`.

### Your Environment

- Environment: Windows 10 20H2 x64 with Node.js 14.15.1 LTS.
- Node.js runs in a ES Modules environment

### Steps to Reproduce

Run the example in a ES Modules environment.

**Comment by gomse** [comment]
`node_modules/@marko/express/dist/cjs/index.js`:
- line 9: `exports.default` to `module.exports`

i wanna fix it ;)

**Comment by GingerAdonis** [comment]
Bump. Due to this bug the Marko documentation example doesn't work.
